name: Safe Core Wraps Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  Release:
    if: |
      github.event.pull_request.merged &&
      endsWith(github.event.pull_request.title, '/workflows/release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Install protocol kit dependencies
        run: yarn
        working-directory: ./wraps/protocol-kit

      - name: Build protocol kit
        run: yarn build
        working-directory: ./wraps/protocol-kit

      - name: Deploy protocol kit
        run: yarn deploy
        working-directory: ./wraps/protocol-kit
        env:
          POLYWRAP_WRAPSCAN_AUTH_HEADER_PROD: ${{secrets.POLYWRAP_WRAPSCAN_AUTH_HEADER_PROD}}

      - name: Install relay kit dependencies
        run: yarn
        working-directory: ./wraps/relay-kit

      - name: Build relay kit
        run: yarn build
        working-directory: ./wraps/relay-kit

      - name: Deploy relay kit
        run: yarn deploy
        working-directory: ./wraps/relay-kit
        env:
          POLYWRAP_WRAPSCAN_AUTH_HEADER_PROD: ${{secrets.POLYWRAP_WRAPSCAN_AUTH_HEADER_PROD}}

      - name: Install account abstraction kit dependencies
        run: yarn
        working-directory: ./wraps/account-abstraction-kit

      - name: Build account abstraction kit
        run: yarn build
        working-directory: ./wraps/account-abstraction-kit

      - name: Deploy account abstraction kit
        run: yarn deploy
        working-directory: ./wraps/account-abstraction-kit
        env:
          POLYWRAP_WRAPSCAN_AUTH_HEADER_PROD: ${{secrets.POLYWRAP_WRAPSCAN_AUTH_HEADER_PROD}}

      - uses: peter-evans/create-pull-request@v3
        with:
          branch: update-uri-pr-${{github.event.number}}
          commit-message: "chore: update wrap uris"
          title: "chore: update wrap uris"
          body: "Triggered by: https://github.com/${{github.repository}}/pull/${{github.event.number}}"
